version: "3"
services:

  111wbs_dev:
    container_name: 111wbs_dev
    build: ../111wbs_dev
    volumes:
      - ../../s_01_src/110wbs_src:/usr/src/app
      - wbs-vol:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true # Hot-reload
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    networks:
      - django_react_postgresql_example_network
    # platform: linux/x86_64

volumes:
  wbs-vol:

networks:
  django_react_postgresql_example_network:
    driver: bridge