# Generated by Django 4.1 on 2023-07-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferList',
            fields=[
                ('offer_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='オファーID')),
                ('account_id', models.CharField(max_length=64, verbose_name='ユーザID')),
                ('offer_type', models.CharField(max_length=1, verbose_name='オファー種別')),
                ('offer_title', models.TextField(verbose_name='オファー題目')),
                ('offer_severity', models.TextField(verbose_name='オファー優先度')),
                ('offer_catagory', models.TextField(verbose_name='オファー・カテゴリ')),
                ('offer_location', models.TextField(verbose_name='オファー場所')),
                ('offer_status', models.CharField(max_length=1, verbose_name='オファーStatus')),
                ('offer_text', models.CharField(max_length=140, verbose_name='オファー文')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': 'オファー台帳',
                'verbose_name_plural': 'オファー台帳（catalog）',
                'db_table': 'offer_list',
            },
        ),
    ]
